language: node_js
env:
- NODE_ENV=test
node_js:
- '10'
script:
- yarn
- yarn add admin-bro@2.0.1
- yarn run build
- yarn run lint
deploy:
  skip_cleanup: true
  provider: npm
  # tag: beta
  email: wojciech.g.krysiak@gmail.com
  api_key:
    secure: oXX0r6Ua9Oal0ESZVzYL6xtjHJ31grqdGD4Ejx6/ci14qoCYO6+LgtYPC45rKXlj6FVq0IOSJOvXUCe5xZ/JbrKXsMRa50cX+psbN2/0IdjhykuXHT69ZWrxDfwmkiRp0I/IBBQtJP6mXu4zFbarU+uwFYZv1LzgepNtrSR3PpprHzEsFVBFSu8nCMx+8YnSkYQGBwc1lR73PUBiVz8ayS0JPetuAGQX4eO/5Hgao5H8Zy+20rV5gNyBV/2Ibj0IOZY19x8bmjb/nYayA/v75l6wWU734RAskV9nr/ePUoG9K0Ds6p6Wj68AJIS026aNyeutfxX+cbxm2JWEoUvPjWF143JkXtRpRcnzAr8gSIpv2XlfLCz9c4Ip3NB8Xa0FNt9VZ+07/MywsG7CZFFuC03lxttKcEYCckwM1cX+5ifmSGDgY/duX2IxX7KuQY6jankgc2T9o4xz2OgBHPoManRkDA8GEQtQZpU7VG3M6IbFEw908NpiPDGHD908w18T160vtrNC7FckM0o8FuowXGLP/UMd3cBXgoYTK+IdJerT1B+5Fxvy1nBVEWwoeoFNkE7Aa+8vwhcrKG4Nu1yHpAPHIdtlZwqANmxAxyk/Rn1EEpshaT+5qfH4O6cFs4PoygVNg+pUAdIgKY5zxn2YnhSLawo1zmGr9kdB3TRhHvM=
  on:
    tags: true
    repo: SoftwareBrothers/admin-bro-firebase-functions
notifications:
  slack:
    secure: TIQM/IW5CQ4ba0cLJwP2HG5twDG7G+jTc+Exx2sO22zOpW+8kWlytbFIjNXa2cWijDkON8nUvRuAW1niK6WAYlqI3PFswKjWQNCqwE6MR3TlLtVT8isHQiWUFZRV6A+RxNU9/yqkWnu6qAVySk2Mf8a0AfB7hLXjQqqL21ZLIdbO5KBRH07Qclg24UUfBr4A1LEAf+8DJtblh9/Bnu/XdjI25SoTAzBZOl0pOEGUmXf1B+TW7IeL9wsj55EGavJObifM4fkNa/1S2YRqmKj79Og74AvnjHVhTodX9CCouFnQZUCIhIGK1gcjHnpV24mzMSkLjpFfV0uFKi0sRT5LUHCrmv1vs/qTfY0W8ru2kaRB8VyuiYnFUGezK6li9MsLUoNVy0BjQSjhaOyqeNPrk3bhDnnzadiWEJPfsHYkSF4FlBvtSbq3TEAQQkper93N0nlatDPDlBbozAOfJy2G+LHm5sLhepySOdhLpes/hIbYfphNsmHy/3ZF8ZTHwNKTCwycLveea+DqQu+vHpktppHf71kmIzGl8IlY2DkLUnTumEuan/4FiGkJ83KMaXVb63A+mdTAEf8x9t0N3IQTdPshSIYftKGd5rKbAPTvCpGY9phofwO1EckKCnjFonfoMm/Il6PevNGsbzfLCDkchctyy1XEwc2pGsA2FPvZXfY=
